server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: sayHi
        uri: https://www.baidu.com
        # 路由匹配规则
        predicates:
          - Path=/toSayHi
        filters:
          - StripPrefix= 1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

